language: ruby
cache: bundler

rvm:
  - "2.1.1"
  - "2.0.0"
  - "1.9.3"



bundler_args: --without development

branches:
  only:
    - master

notifications:
  email:
    - ericdejonckheere@gmail.com
